spring:
    jpa:
        database: mysql
        hibernate:
                ddl-auto: validate
                naming:
                    implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: false
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
    datasource:
        url: jdbc:mysql://mysql:3306/knowledgedb
        username: atm
        password: root
        driverClassName: com.mysql.jdbc.Driver